name: Build Feature

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - master

jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11


        run: |
          echo "pulling and checking out from git repository"

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.0
            